In [2]:
import numpy as np

In [3]:
chessboard = -np.array([
            [990, -40, 300, 200, 200, 300, -40, 990],
            [-40, -400, 4, 2, 2, 4, -400, -40],
            [300, 4, 5, 1, 1, 5, 4, 300],
            [200, 2, 1, 0, 0, 1, 2, 200],
            [200, 2, 1, 0, 0, 1, 2, 200],
            [300, 4, 5, 1, 1, 5, 4, 300],
            [-40, -400, 4, 2, 2, 4, -400, -40],
            [990, -40, 300, 200, 200, 300, -40, 990]
        ])
chessboard

array([[-990,   40, -300, -200, -200, -300,   40, -990],
       [  40,  400,   -4,   -2,   -2,   -4,  400,   40],
       [-300,   -4,   -5,   -1,   -1,   -5,   -4, -300],
       [-200,   -2,   -1,    0,    0,   -1,   -2, -200],
       [-200,   -2,   -1,    0,    0,   -1,   -2, -200],
       [-300,   -4,   -5,   -1,   -1,   -5,   -4, -300],
       [  40,  400,   -4,   -2,   -2,   -4,  400,   40],
       [-990,   40, -300, -200, -200, -300,   40, -990]])

In [5]:
rest = np.where(chessboard == 0)
rest = list(zip(rest[0], rest[1]))

In [6]:
rest

[(3, 3), (3, 4), (4, 3), (4, 4)]

In [7]:
for x, y in rest:
    print(x)
    print(y)

3
3
3
4
4
3
4
4


In [4]:
weight_table = -np.array([
        [-120, 50, -48, -42, -42, -48, 50, -120],
        [50, 77, -8, -6, -6, -8, 77, 50],
        [-48, -8, -5, -4, -4, -5, -8, -48],
        [-42, -6, -4, -3, -3, -4, -6, -42],
        [-42, -6, -4, -3, -3, -4, -6, -42],
        [-48, -8, -5, -4, -4, -5, -8, -48],
        [50, 77, -8, -6, -6, -8, 77, 50],
        [-120, 50, -48, -42, -42, -48, 50, -120]
    ])
weight_table

array([[120, -50,  48,  42,  42,  48, -50, 120],
       [-50, -77,   8,   6,   6,   8, -77, -50],
       [ 48,   8,   5,   4,   4,   5,   8,  48],
       [ 42,   6,   4,   3,   3,   4,   6,  42],
       [ 42,   6,   4,   3,   3,   4,   6,  42],
       [ 48,   8,   5,   4,   4,   5,   8,  48],
       [-50, -77,   8,   6,   6,   8, -77, -50],
       [120, -50,  48,  42,  42,  48, -50, 120]])

In [7]:
weight_table = weight_table + 3

In [9]:
weight_table = np.array([[120, -50,  48,  42,  42,  48, -50, 120],
       [-50, -77,   8,   6,   6,   8, -77, -50],
       [ 48,   8,   5,   4,   4,   5,   8,  48],
       [ 42,   6,   4,   3,   3,   4,   6,  42],
       [ 42,   6,   4,   3,   3,   4,   6,  42],
       [ 48,   8,   5,   4,   4,   5,   8,  48],
       [-50, -77,   8,   6,   6,   8, -77, -50],
       [120, -50,  48,  42,  42,  48, -50, 120]])
weight_table

array([[120, -50,  48,  42,  42,  48, -50, 120],
       [-50, -77,   8,   6,   6,   8, -77, -50],
       [ 48,   8,   5,   4,   4,   5,   8,  48],
       [ 42,   6,   4,   3,   3,   4,   6,  42],
       [ 42,   6,   4,   3,   3,   4,   6,  42],
       [ 48,   8,   5,   4,   4,   5,   8,  48],
       [-50, -77,   8,   6,   6,   8, -77, -50],
       [120, -50,  48,  42,  42,  48, -50, 120]])

In [1]:
weight_list = (120, -50, 48, 42, -77, 8, 6, 5, 4, 3)
weight_list

(120, -50, 48, 42, -77, 8, 6, 5, 4, 3)